app_DRF_avail_report/urls.py
from django.urls import path
from . import views

app_name = 'app_upload_DRF_avail_report'

urlpatterns =[
path('DRF_avail_report/', views.DRF_Report,name='DRF_Report'),

]

app_upload_test/urls.py
from django.urls import path
from . import views

app_name = 'app_upload_test'

urlpatterns =[
path('upload_test/', views.UploadTestView,name='upload_test'),

]

project_DRMIS_Tools/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

MM_tools_list =[
path('app_upload_test', include('app_upload_test.urls',namespace='app_upload_test')),
path('app_DRF_avail_report', include('app_DRF_avail_report.urls',namespace='app_DRF_avail_report'))

]

FI_tools_list =[

]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('about',views.AboutPage.as_view(),name='about'),
    path('MM_tools/',views.MMToolsView.as_view(),name='MM_Tools'),
    path('FI_tools/',views.FIToolsView.as_view(),name='FI_Tools'),
] + MM_tools_list + FI_tools_list

templates/about.html
{% extends 'base.html' %}

{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron 8">
    <h1>about page</h1><br>
    <p>stuff</p>
  </div>
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>DRMIS Tools</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <!-- Custom styles for this template -->

<body>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark header">
   <a class="navbar-brand" href=""></a>

<a class="navbar-brand" href="{% url 'home' %}">Home</a>

 <ul class="navbar-nav mr-auto">

   <li class="nav-item active">
     <a class="nav-link" href="{% url 'MM_Tools' %}">MM Tools</a>
   </li>

   <li class="nav-item active">
     <a class="nav-link" href="{% url 'FI_Tools' %}">FI Tools</a>
   </li>

    <li class="nav-item active">
      <a class="nav-link" href="{% url 'about' %}">About</a>
    </li>


 </ul>

</nav>

{% block body_block %}

{% endblock %}


  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block body_block %}

{% load static %}

<div class="container">
  <div class="jumbotron 8">
    <h1>Welcome to DRMIS Tools</h1><br>
    <p>For all inquiries regarding this website please contact me at <strong>alfa.budiman@forces.gc.ca</strong>.</p>
  </div>
</div>


{% endblock %}

templates/tools_FI.html
{% extends "base.html" %}

{% block body_block %}

<div class="row">

  <div class="col-2">
    <div class="list-group" >
      <a class="list-group-item list-group-item-action" id="" data-toggle="list" href="" role="tab" aria-controls="profile">placeholder1</a>
      <a class="list-group-item list-group-item-action" id="" data-toggle="list" href="" role="tab" aria-controls="profile">placeholder2</a>

    </div>
  </div>


    <div class="col-8">

      <div class="jumbotron">
{% block tool_block %}

      <h1 class="display-4"><strong>DRMIS FI Tools overview</strong></h1>
      <br>
      <p>Note: Each input must be entered <strong>exactly</strong> as described or the calculation will not work</p>

      <br>
      <p><strong>stuff: </strong>does stuff</p>
      <p><strong>more stuff: </strong>more stuff</p>


{% endblock %}
</div><!-- /.jumbotron -->

{% endblock %}

templates/tools_MM.html
{% extends "base.html" %}

{% block body_block %}

<div class="row">

  <div class="col-2">
    <div class="list-group" >
      <a class="list-group-item list-group-item-action" id="" data-toggle="list" href="{%url 'app_DRF_avail_report:DRF_Report'%}" role="tab" aria-controls="profile">DRF Availability Report</a>
      <a class="list-group-item list-group-item-action" id="" data-toggle="list" href="{% url 'app_upload_test:upload_test'%}" role="tab" aria-controls="profile">Upload Test</a>

    </div>
  </div>


    <div class="col-8">

      <div class="jumbotron">
{% block tool_block %}

      <h1 class="display-4"><strong>DRMIS MM Tools Overview</strong></h1>
      <br>
      <p>Note: Each input must be entered <strong>exactly</strong> as described or the calculation will not work</p>

      <br>
      <p><strong>DRF Availability Report: </strong>does stuff</p>
      <p><strong>Upload Test: </strong>does stuff</p>


{% endblock %}
</div><!-- /.jumbotron -->

{% endblock %}